# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = "test-devops-box"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1000"
    vb.cpus = 1
  end

  # Install git, hugo and fortune
  # We want to use 'git worktree', and there is a bug in
  # git 2.7.4(https://discourse.gohugo.io/t/github-deployment-using-worktrees-failing/5918/5)
  # So we use the ppa:git-core instead
  config.vm.provision "shell", inline: <<-SHELL
    add-apt-repository ppa:git-core/ppa -y
    apt-get update
    apt-get install git hugo fortune-mod -y
  SHELL
  
  # Install Golang and some deps
  config.vm.provision "shell", inline: <<-SHELL
    apt-get install golang-1.9 wamerican -y
    echo "export GOROOT=/usr/lib/go-1.9" >> /etc/profile
    echo "export GOPATH=/home/ubuntu/workspace" >> /etc/profile
    echo 'export PATH=$PATH:$GOROOT/bin' >> /etc/profile
    echo 'export PATH=$PATH:$GOPATH/bin' >> /etc/profile
    source /etc/profile
  SHELL

  # Upload the init script
  config.vm.provision "file", source: "./init.sh", destination: "~/init.sh"
end
